### ISSUE TITLE
"systolic_array_synth.csv" is missing

### ISSUE THREAD

**Issue by zhijian-liu** [hsharma35/bitfusion#1]

**Comment by wxbbuaa2011** [comment]
你跑起来了吗？他们做的好好啊

**Comment by wxbbuaa2011** [comment]
I also can't find the file "systolic_array_synth.csv". Can you provide?

**Comment by wxbbuaa2011** [comment]
@hsharma35 Can you provide the file "systolic_array_synth.csv"?

**Comment by zhijian-liu** [comment]
Hi @wxbbuaa2011, you should be able to figure out there values from the results in "bitfusion-generate-graphs.ipynb". Hope this helps!

**Comment by wxbbuaa2011** [comment]
Thank you,
